config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'home', 'action' => 'index']);    
    
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);    
    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('admin', function ($routes) {
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.

    $routes->connect('/', ['controller' => 'users', 'action' => 'login']);

    $routes->fallbacks(DashedRoute::class); 
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/PostsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Event\Event;
use ArrayObject;
use Cake\Utility\Text;

/**
 * Posts Model
 *
 * @property \App\Model\Table\CategoriesTable|\Cake\ORM\Association\BelongsTo $Categories
 *
 * @method \App\Model\Entity\Post get($primaryKey, $options = [])
 * @method \App\Model\Entity\Post newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Post[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Post|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Post patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Post[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Post findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PostsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('posts');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->addBehavior('Proffer.Proffer', [
            'photo' => [    // The name of your upload field
                'root' => WWW_ROOT . 'files', // Customise the root upload folder here, or omit to use the default
                'dir' => 'photo_dir',   // The name of the field to store the folder
                'thumbnailSizes' => [ // Declare your thumbnails
                    'square' => [   // Define the prefix of your thumbnail
                        'w' => 200, // Width
                        'h' => 200, // Height
                        'jpeg_quality'  => 100
                    ],
                    'portrait' => [     // Define a second thumbnail
                        'w' => 100,
                        'h' => 300
                    ],
                ],
                'thumbnailMethod' => 'gd'   // Options are Imagick or Gd
            ]
        ]);

        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('name')
            ->requirePresence('name', 'create')
            ->notEmpty('name');

        $validator
            ->scalar('author')
            ->requirePresence('author', 'create')
            ->notEmpty('author');
      /*  $validator
            ->scalar('permanlink')
            ->requirePresence('permanlink', 'create')
            ->notEmpty('permanlink');*/
        $validator
            ->scalar('intro')
            ->requirePresence('intro', 'create')
            ->notEmpty('intro');

        $validator
            ->scalar('description')
            ->requirePresence('description', 'create')
            ->allowEmpty('description');

        $validator
            ->scalar('tags')
            ->requirePresence('tags', 'create')
            ->allowEmpty('tags');

        $validator
            ->scalar('caption_image')
            ->requirePresence('caption_image', 'create')
            ->notEmpty('caption_image');

        $validator
            ->scalar('meta_title')
            ->requirePresence('meta_title', 'create')
            ->notEmpty('meta_title');

        $validator
            ->scalar('meta_description')
            ->requirePresence('meta_description', 'create')
            ->notEmpty('meta_description');

        $validator
            ->scalar('facebook_title')
            ->requirePresence('facebook_title', 'create')
            ->notEmpty('facebook_title');

        $validator
            ->scalar('facebook_description')
            ->requirePresence('facebook_description', 'create')
            ->notEmpty('facebook_description');

        $validator
            ->scalar('twitter_title')
            ->requirePresence('twitter_title', 'create')
            ->notEmpty('twitter_title');

        $validator
            ->scalar('twitter_description')
            ->requirePresence('twitter_description', 'create')
            ->notEmpty('twitter_description');

        $validator
            ->requirePresence('photo', 'create')
            ->notEmpty('photo','create')
            ->allowEmpty('photo', 'update');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['category_id'], 'Categories'));

        return $rules;
    }

    public function beforeMarshal(Event $event, ArrayObject $data, ArrayObject $options)
    {
        if (isset($data['name'])) {
            $data['permalink'] = Text::slug($data['name']);
        }

        if (!empty($data['tags'])) {
            $data['tags'] = implode(',', $data['tags']);
        }

    }
}

src/Template/Layout/ajax.ctp
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @since         0.10.0
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

echo $this->fetch('content');

src/Template/Layout/default.ctp
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @since         0.10.0
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

$cakeDescription = 'CakePHP: the rapid development php framework';
?>
<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>
    <?= $this->Html->charset() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>
        <?= @$title_for_layout; ?>
    </title>
    <?php if (!empty($description_for_layout)): ?>
    <meta name="description" content="<?= @$description_for_layout ?>">
    <?php endif ?>

    <?php if (!empty($keywords)): ?>
	<meta name="keywords" content="<?= @$keywords ?>">
    <?php endif ?>

    <?= $this->Html->meta('favicon.png','img/favicon.png',['type' => 'icon']); ?>
    
    <?php if (!empty($facebookMetas)): ?>
	<meta charset="UTF-8">
	<meta property="og:type" content="article">
	<meta property="og:site_name" content="bpoinsight">
    <meta property="og:url" content="<?= $this->Url->build($post->category->permalink.'/'.$post->permalink,true) ?>">
    <meta property="og:title" content="<?= @$facebookMetas['site_name'] ?>">
	<meta property="og:description" content="<?= @$facebookMetas['description'] ?>">
	<meta property="og:image" content="<?= $this->Url->build(@$facebookMetas['image'],true) ?>">
	<?php endif ?>
	<?php if (!empty($twitterMetas)): ?>
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:site" content="@bpoinsight" />
	<meta name="twitter:title" content="<?= @$twitterMetas['site_name'] ?>" />
	<meta name="twitter:description" content="<?= @$twitterMetas['description'] ?>" />
	<meta name="twitter:image" content="<?= $this->Url->build(@$twitterMetas['image'],true) ?>" />
	<?php endif ?>

    <link rel="stylesheet" href="<?php echo $this->Elixir->version('css/default.css'); ?>">

    <?= $this->fetch('meta') ?>
    <?= $this->fetch('css') ?>
    <?= $this->fetch('script') ?>
</head>
<body>
    <header class="Header">
        <?= $this->element('Default/header'); ?>
    </header>
    <div id="content" class="MainContent">
        <?= $this->fetch('content') ?>
    </div>
    <footer class="Footer">
        <?= $this->element('Default/footer'); ?>
    </footer>
    <?php $this->TinymceElfinder->defineElfinderBrowser()?>
    <?= $this->Html->script('all.js'); ?>
    <script>
        $(document).ready(function(){
            $("#Audio").trigger('pause');
            $(".Player").on("click", function(event) {
                event.preventDefault();
                var task = $(this).attr('data-task');
                if(task == 'play'){
                    $("#Audio").trigger('load');
                    $(".Play").attr('data-task','stop');
                    $(".Menu-player").attr('data-task','stop');
                    $(".Play").children().attr('class','fas fa-pause');
                    $(".Menu-player").children().attr('class','fas fa-volume-up');
                }
                if(task == 'stop'){
                    $("#Audio").trigger('pause');
                    $(".Play").attr('data-task','play');
                    $(".Menu-player").attr('data-task','play');
                    $(".Play").children().attr('class','fas fa-play');
                    $(".Menu-player").children().attr('class','fas fa-volume-off');
                }
            }); 

        });
    </script>
</body>
</html>

src/Template/Layout/error.ctp
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @since         0.10.0
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
?>
<!DOCTYPE html>
<html>
<head>
    <?= $this->Html->charset() ?>
    <title>
        <?= $this->fetch('title') ?>
    </title>
    <?= $this->Html->meta('icon') ?>

    <?= $this->Html->css('base.css') ?>
    <?= $this->Html->css('cake.css') ?>

    <?= $this->fetch('meta') ?>
    <?= $this->fetch('css') ?>
    <?= $this->fetch('script') ?>
</head>
<body>
    <div id="container">
        <div id="header">
            <h1><?= __('Error') ?></h1>
        </div>
        <div id="content">
            <?= $this->Flash->render() ?>

            <?= $this->fetch('content') ?>
        </div>
        <div id="footer">
            <?= $this->Html->link(__('Back'), 'javascript:history.back()') ?>
        </div>
    </div>
</body>
</html>